# Instructions from https://wiki.postgresql.org/wiki/YUM_Installation

- lineinfile: dest=/etc/yum.repos.d/CentOS-Base.repo insertafter="name.+Base" line="exclude=postgresql*" state=present
- lineinfile: dest=/etc/yum.repos.d/CentOS-Base.repo insertafter="name.+Updates" line="exclude= postgresql*" state=present

- name: Install pgdg rpm file
  yum: name=http://yum.postgresql.org/9.4/redhat/rhel-{{ ansible_distribution_major_version }}-x86_64/pgdg-centos94-9.4-1.noarch.rpm state=present

- name: Install PostgreSQL
  yum: name=postgresql94-server state=present

- name: Initialize
  shell: /usr/pgsql-9.4/bin/postgresql94-setup initdb

- name: Startup
  service: name=postgresql-9.4 state=started enabled=yes
