- hosts: all
  gather_facts: False
  
  pre_tasks:
  - name: add resolve before start provision
    raw: sudo echo "nameserver 114.114.114.114" >/etc/resolv.conf

  - name: install python 2 suit ansible
    raw: test -e /usr/bin/python || (apt -y update && apt install -y aptitude python-minimal python-pip)

  roles:
    - initenv
    - nginx
    - postconfig
