---
  - hosts: localhost
    roles:
      - ansible
    tasks:
      - name: add target server name into staging inventory
        template: src=./staging.j2 dest=./staging mode=0755
      - name: prepare hostname in main playbook
        template: src=./main.j2 dest=./main.yml mode=755
