#Instruction from https://getkong.org/install/centos/
- name: install epel-release
  yum: name=epel-release state=latest

- name: set kong_rpm
  set_fact: kong_rpm="kong-0.8.1.el{{ ansible_distribution_major_version }}.noarch.rpm"

- name: get kong rpm
  get_url: url=https://github.com/Mashape/kong/releases/download/0.8.1/{{ kong_rpm }} dest=/usr/local/

- name: install kong rpm
  yum: name=/usr/local/{{ kong_rpm }} disable_gpg_check=yes state=present
