baseURL = "/"
languageCode = "en-us"
title = "Wiredcraft | Demo"
theme = "yinyang"

[author]
  name = "Wiredcraft"
  homepage = "https://joway.io/"

[params]
extraHead = ''
mainSections = ["posts"]
favicon = "https://wiredcraft.com/assets/favicons/favicon-32x32.png"

version = "0.18.0"
