---
- name: install dev dependencies
  yum:
    state: installed
    name: "{{ packages }}"
  vars:
    packages:
    - git-core
    - zlib
    - zlib-devel
    - gcc-c++
    - patch
    - readline
    - readline-devel
    - libyaml-devel
    - libffi-devel
    - openssl-devel
    - make
    - bzip2
    - autoconf
    - automake
    - libtool
    - bison
    - curl
    - sqlite-devel
    - httpd-tools
    - ruby-devel
    - epel-release

- name: install both rbenv and ruby-build
  become: "{{ remote_user }}"
  shell: |
    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
    source ~/.bashrc
    curl -sL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash -
    echo 'eval "$(rbenv init -)"' >> ~/.bashrc
  args:
    chdir: /home/vagrant

- name: install ruby
  become: "{{ remote_user }}"
  shell: |
    source ~/.bashrc
    rbenv install {{ruby}}
    rbenv global {{ruby}}
  args:
    chdir: /home/vagrant

- name: install jekyll
  become: "{{ remote_user }}"
  shell: |
    source ~/.bashrc
    gem install bundler jekyll
  args:
    chdir: /home/vagrant

- name: setenforce permissive
  shell: |
    setenforce permissive

