---
- name: Install epel 
  yum:
    state: installed
    name: epel-release
    update_cache: yes

- name: Install nginx 
  yum:
    state: installed
    name: nginx
    update_cache: yes


- name: Copy nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root

- name: Create sites-available folder
  file:
    path: "/etc/nginx/sites-available"
    owner: nginx
    group: nginx
    mode: 0755
    state: directory

- name: Create sites-enabled folder
  file:
    path: "/etc/nginx/sites-enabled"
    owner: nginx
    group: nginx
    mode: 0755
    state: directory

- name: Create log folders, dev/stage roots
  file:
    path: "{{ item }}"
    owner: nginx
    group: nginx
    mode: 0755
    state: directory
  with_items:
    - "{{ logs_dev_root }}"
    - "{{ logs_stage_root }}"
    - "{{ www_dev_root }}"
    - "{{ www_dev_root_latest_init }}"
    - "{{ www_stage_root }}"
    - "{{ www_stage_root_latest_init }}"

- name: Deployment root sites symlinks
  file:
    state: link
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: 0755
    force: yes
  with_items:
    - { src: "{{ www_dev_root_latest_init }}", dest: "{{ www_dev_root_latest }}" }
    - { src: "{{ www_stage_root_latest_init }}", dest: "{{ www_stage_root_latest }}" }
  

- name: Create dev/stage sites nginx settings
  template:
    src: "devopstest_{{ item }}.j2"
    dest: "/etc/nginx/sites-available/devopstest_{{ item }}.conf"
    owner: nginx
    group: nginx
    mode: 0755
  with_items:
    - "dev"
    - "stage"

- name: Nginx sites symlink
  file:
    state: link
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: yes
  with_items:
    - { src: "/etc/nginx/sites-available/devopstest_dev.conf", dest: "/etc/nginx/sites-enabled/devopstest_dev.conf" }
    - { src: "/etc/nginx/sites-available/devopstest_stage.conf", dest: "/etc/nginx/sites-enabled/devopstest_stage.conf" }
  

- name: Start and enable nginx 
  shell: |
    systemctl start nginx
    systemctl enable nginx