---
- name: Install dev dependencies
  yum:
    state: installed
    name: "{{ packages }}"
  vars:
    packages:
    - wget
    - git-core

- name: Add yum hugo.repo
  get_url:
    url: https://copr.fedorainfracloud.org/coprs/daftaupe/hugo/repo/epel-7/daftaupe-hugo-epel-7.repo
    dest: /etc/yum.repos.d/hugo.repo
    mode: "0644"

- name: Install hugo 
  yum:
    state: installed
    name: hugo
    update_cache: yes

- name: Get fortune rpm 
  get_url:
    url: https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/f/fortune-mod-1.99.1-17.el7.x86_64.rpm
    dest: "{{ fortune_file }}"
    mode: "0644"

- name: Install fortune rpm
  shell: |
    yum localinstall -y "{{ fortune_file }}"

- name: Setenforce permissive
  shell: |
    setenforce permissive

