---
- name: Install dev dependencies
  yum:
    state: installed
    name: "{{ packages }}"
  vars:
    packages:
    - wget
    - git-core

- name: Add yum hugo.repo
  shell: |
    wget https://copr.fedorainfracloud.org/coprs/daftaupe/hugo/repo/epel-7/daftaupe-hugo-epel-7.repo -O hugo.repo
  args:
    chdir: /etc/yum.repos.d

- name: Install hugo 
  yum:
    state: installed
    name: hugo
    update_cache: yes


- name: Setenforce permissive
  shell: |
    setenforce permissive

