---
- name: Add git user config
  become: "{{ remote_user }}"
  shell: |
    git config --global user.name "WiredCraft DevOps"
    git config --global user.email wiredcraft@mail.com

- name: Copy ssh key
  copy:
    src: wiredcraft_devops_test_key
    dest: "{{ ssh_key_path }}"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: '0600'

- name: Copy ssh config file
  copy:
    src: config
    dest: "{{ ssh_config }}"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: '0700'

- name: Prepare push repo
  become: "{{ remote_user }}"
  git:
    clone: yes
    repo: "{{ git_origin }}"
    dest: "{{ push_repo }}"

- name: Prepare pull repo
  become: "{{ remote_user }}"
  shell: |
    cp -r "{{ push_repo }}" "{{ pull_repo }}"


- name: Initial warmup for dev and stage websites
  become: "{{ remote_user }}"
  shell: |
    cd "{{ pull_repo }}"

    LOCAL_BRANCH=$(git rev-parse --abbrev-ref HEAD)
    TAG=$(git tag | sort -V | tail -1)
    REV=$(git rev-parse HEAD)

    git checkout "${REV}"
    cp -r ./website/public/* "{{ www_dev_root_latest_init }}"

    git checkout "${TAG}"
    cp -r ./website/public/* "{{ www_stage_root_latest_init }}" 

    git checkout "${LOCAL_BRANCH}"
    sudo systemctl reload nginx.service 