# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Hugo Product Launch"
license = "Creative Commons Attribution 4.0 International Public License (CC BY 4.0)"
licenselink = "https://github.com/janraasch/hugo-product-launch/blob/master/LICENSE"
description = "A Hugo theme for young start-ups, product launches, and »coming soon«-websites. Includes contact form & newsletter sign up via Netlify. Deploy with one click!"
homepage = "https://github.com/janraasch/hugo-product-launch"
tags = [
  "coming soon",
  "clean",
  "business",
  "contact",
  "contact form",
  "company",
  "landing page",
  "launch page",
  "netlify",
  "newsletter",
  "onepage",
  "one page",
  "personal",
  "projects",
  "product",
  "simple",
  "single page",
  "single product",
  "starter",
  "tailwindcss",
  "responsive",
  "theme"
]
features = [
  "cover-image",
  "favicon",
  "responsive",
  "fast",
  "tailwindcss",
  "purgecss",
  "contact form",
  "newsletter sign-up",
  "netlify",
  "netlify forms"
]
min_version = "0.69.0"

[author]
  name = "Jan Raasch"
  homepage = "https://www.janraasch.com"
