- name: Install git
  action: apt pkg=git-core state=installed 
- name: Authenticate on GitHub
  template: src=.netrc dest={{http_user_home}}/.netrc mode=0600 owner={{http_user}} group={{http_user}}
- name: Set identity on Git
  template: src=.gitconfig dest={{http_user_home}}/.gitconfig mode=0600 owner={{http_user}} group={{http_user}}
