- name: Install nginx
  yum:
    name: nginx
    state: present
- name: Create directory
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - '{{ location_dev }}'
    - '{{ location_staging }}'
- name: Copy nginx configuration
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
