- name: Create http_user
  user: name={{http_user}} group={{http_user}}
- name: Create dev directory
  file: dest={{dev_directory}} mode=0775 owner={{http_user}} group={{http_user}} state=directory
- name: Clone git repo to dev directory
  git:
    repo: "{{git_repo_url}}"
    dest: "{{dev_directory}}"
    clone: yes
- name: Create staging directory
  file: dest={{staging_directory}} mode=0775 owner={{http_user}} group={{http_user}} state=directory 
- name: Clone git repo to staging directory
  git:
    repo: "{{git_repo_url}}"
    dest: "{{staging_directory}}"
    clone: yes
