name: go_script_unit_test
on: pill_request
jobs:
  build:
    name: Set up go ENV
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Test
        run: go test -v .

  




