apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-API
  labels:
    service-monitor: test-API
spec:
  selector:
    matchLabels:
      app: sample-metrics-app
  endpoints:
  - port: web
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: test-API-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-API
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      target:
        kind: Service
        name: test-API
      metricName: user_number
      targetValue: 10000
