apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mock-api-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mock-api-server
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
