apiVersion: v1
kind: Service
metadata:
  labels:
    app: wiredcraft-test-mockapi
  name: wiredcraft-test-mockapi
spec:
  ports:
  - name: svc
    port: 80
    protocol: TCP
    targetPort: 8100
  selector:
    app: wiredcraft-test-mockapi
