name: hugo

on:
  push:
    branches:
      - develop  # Set a branch to deploy
    # tags:
    #   - '*.*.*'

jobs:
  hugo:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          # hugo-version: 'latest'
          hugo-version: 'v0.80.0'
          extended: true

      # Step 3 - Clean and don't fail
      - name: Clean public directory
        run: rm -rf public

      # - name: Cache dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: /tmp/hugo_cache
      #     key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
      #     restore-keys: |
      #       ${{ runner.os }}-hugomod-

      - name: Build
        run: hugo --theme=erblog
        #  --gc --minify --cleanDestinationDir

      # - name: Prepare tag
      #   id: prepare_tag
      #   if: startsWith(github.ref, 'refs/tags/')
      #   run: |
      #     TAG_NAME="${GITHUB_REF##refs/tags/}"
      #     echo "::set-output name=tag_name::${TAG_NAME}"
      #     echo "::set-output name=deploy_tag_name::deploy-${TAG_NAME}"

      - name: Deploy
        if: success() && github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v3
        with:
          user_name: chuzhu
          user_email: robert010256@gmail.com
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # commit_message: ${{ github.event.head_commit.message }}
          # tag_name: ${{ steps.prepare_tag.outputs.deploy_tag_name }}
          # tag_message: 'Deployment ${{ steps.prepare_tag.outputs.tag_name }}'