name: hugo

on:
  push:
    branches:
      - staging
    tags:
      - '*.*.*' 

jobs:
  hugo:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          # hugo-version: 'latest'
          hugo-version: '0.80.0'
          extended: true

      # Step 3 - Clean and don't fail
      - name: Clean public directory
        run: rm -rf public

      # - name: Cache dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: /tmp/hugo_cache
      #     key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
      #     restore-keys: |
      #       ${{ runner.os }}-hugomod-

      - name: Build
        run: hugo -t erblog --gc --minify --cleanDestinationDir

      - name: Prepare tag
        id: prepare_tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_NAME="${GITHUB_REF##refs/tags/}"
          echo "::set-output name=tag_name::${TAG_NAME}"

      - name: Deploy
        if: success() && github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v3
        with:
          user_name: chuzhu
          user_email: robert010256@gmail.com
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: main
          external_repository: robertchu1205/robertchu1205.github.io
          # deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          # commit_message: 'Staging: ${{ github.event.head_commit.message }}'
          commit_message: 'Staging: ${{ steps.prepare_tag.outputs.tag_name }}'
          tag_name: ${{ steps.prepare_tag.outputs.tag_name }}
          tag_message: 'Staging: ${{ steps.prepare_tag.outputs.tag_name }}'