name: Publish dev
on:
  push:
    branches:
      - interview
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.75.1'
      - name: Build
        run: hugo --minify
      - uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/deploy-dev.yml
          directory: ./
          key: ${{secrets.SSH_KEY}}
          inventory: |
            [all]
            ${{secrets.SERVER_IP}}
          options: |
            --user root
            --verbose
