name: publish staging
on:
  push:
    tags:
      - v*
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.75.1'
      - name: Hugo build
        run: ./cli/hugo_build.sh
      - name: Copy to server
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/deploy-staging.yml
          directory: ./
          key: ${{secrets.SSH_KEY}}
          inventory: |
            [all]
            ${{secrets.SERVER_IP}}
          options: |
            --user root
            --verbose
